name: furniture_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.13
  device_preview: ^1.2.0
  palette_generator: ^0.3.3+5
  auto_size_text: ^3.0.0
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.8.7 # Add this line

flutter:
  generate: true
  uses-material-design: true

assets:
  - assets/icons/
  - assets/images/
flutter_intl:
  enabled: true
