// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyTJRMv2yFbaRl8kD1OWzYtDKuDjLJGlM',
    appId: '1:565824484141:web:d918c479b7e5ff6229d9a4',
    messagingSenderId: '565824484141',
    projectId: 'faramawy-4a899',
    authDomain: 'faramawy-4a899.firebaseapp.com',
    storageBucket: 'faramawy-4a899.firebasestorage.app',
    measurementId: 'G-XCQSGNB20G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFkSNhoJaGWBU9RTMjduv4AZCuGyH-K8A',
    appId: '1:565824484141:android:d5a5d23fb0c6f0bd29d9a4',
    messagingSenderId: '565824484141',
    projectId: 'faramawy-4a899',
    storageBucket: 'faramawy-4a899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDw59x5EhQvb5bQT9cN-sir2Lf2NrziKE',
    appId: '1:565824484141:ios:66bbf01bd8eb790529d9a4',
    messagingSenderId: '565824484141',
    projectId: 'faramawy-4a899',
    storageBucket: 'faramawy-4a899.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDw59x5EhQvb5bQT9cN-sir2Lf2NrziKE',
    appId: '1:565824484141:ios:66bbf01bd8eb790529d9a4',
    messagingSenderId: '565824484141',
    projectId: 'faramawy-4a899',
    storageBucket: 'faramawy-4a899.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyTJRMv2yFbaRl8kD1OWzYtDKuDjLJGlM',
    appId: '1:565824484141:web:6f300d3918735aa329d9a4',
    messagingSenderId: '565824484141',
    projectId: 'faramawy-4a899',
    authDomain: 'faramawy-4a899.firebaseapp.com',
    storageBucket: 'faramawy-4a899.firebasestorage.app',
    measurementId: 'G-YRJFDMZGWZ',
  );

}